#include "pch.h"
#include "..\06_ThreeWayComp\ThreeWayComp_Basic.h"

using ThreeWayComp_Basic::UserProfile;
using ThreeWayComp_Basic::ComparisonBasic;

namespace ThreeWayComp_Basic_Test
{
	class ThreeWayCompTest : public ::testing::Test
	{
	protected:
		ComparisonBasic m_compBasic;
		UserProfile p1 = { 10, "Alice", 95.0 };
		UserProfile p2 = { 20, "Bob", 80.0 };
		UserProfile p3 = { 10, "Alice", 95.0 }; // Identical to p1
		UserProfile p4 = { 10, "Zoe", 95.0 };   // Same ID, different name
	};

	// Test case 1: Equality check (a == b) - Auto-generated from <=>
	TEST_F(ThreeWayCompTest, AutoGenerated_Equality)
	{
		// p1 (ID 10, Alice) == p3 (ID 10, Alice)
		EXPECT_TRUE(m_compBasic.isEqual(p1, p3));
		// p1 != p2
		EXPECT_FALSE(m_compBasic.isEqual(p1, p2));
	}

	// Test case 2: Less Than check (a < b) - Auto-generated from <=>
	TEST_F(ThreeWayCompTest, AutoGenerated_LessThan)
	{
		// p1 (ID 10) < p2 (ID 20)
		EXPECT_TRUE(m_compBasic.isLessThan(p1, p2));

		// p2 (ID 20) < p1 (ID 10) is false
		EXPECT_FALSE(m_compBasic.isLessThan(p2, p1));
	}

	// Test case 3: Greater Than or Equal check (a >= b) - Auto-generated from <=>
	TEST_F(ThreeWayCompTest, AutoGenerated_GreaterOrEqual)
	{
		// p2 (ID 20) >= p1 (ID 10)
		EXPECT_TRUE(m_compBasic.isGreaterOrEqual(p2, p1));
		// p1 (ID 10) >= p3 (ID 10) is true (equivalent)
		EXPECT_TRUE(m_compBasic.isGreaterOrEqual(p1, p3));
	}

	// Test case 4: Lexicographical order (different secondary member)
	TEST_F(ThreeWayCompTest, LexicographicalOrder)
	{
		// p1 (ID 10, Alice) vs p4 (ID 10, Zoe). Comparison falls to the second member (m_name).
		// "Alice" < "Zoe"
		EXPECT_TRUE(m_compBasic.isLessThan(p1, p4));
		EXPECT_FALSE(m_compBasic.isLessThan(p4, p1));
	}
}

