#pragma once
#include <compare>
#include <iostream>
#include <string>

namespace ThreeWayComp_Basic
{
    /**
     * @brief A simple structure to demonstrate the three-way comparison operator (<=>).
     * The default implementation compares members sequentially (lexicographical order).
     */
    struct UserProfile
    {
        int m_id;
        std::string m_name;
        double m_score;

        // 1. Define operator<=> (The Spaceship Operator)
        // "= default" instructs the compiler to automatically generate comparison logic
        // based on all non-static members.
        // std::strong_ordering means that objects being equivalent implies they are interchangeable.
        std::partial_ordering operator<=>(const UserProfile&) const = default;

        // 2. operator== is also automatically generated by the compiler based on operator<=>.
    };

    /**
     * @brief Utility class to demonstrate comparison results.
     */
    class ComparisonBasic
    {
    public:
        // Helper to check if two profiles are less than (a < b)
        bool isLessThan(const UserProfile& a, const UserProfile& b) const
        {
            // The compiler uses the result of operator<=> to evaluate '<'
            return a < b;
        }

        // Helper to check if two profiles are equal (a == b)
        bool isEqual(const UserProfile& a, const UserProfile& b) const
        {
            // Auto-generated operator== is used here.
            return a == b;
        }

        // Helper to check if two profiles are greater than or equal (a >= b)
        bool isGreaterOrEqual(const UserProfile& a, const UserProfile& b) const
        {
            // Generated by the compiler based on operator<=>
            return a >= b;
        }
    };

}
